export function makeTheme(dark) {
  return dark ? {
    bg:              "#0f1117",
    surface:         "#1a1d27",
    surfaceAlt:      "#22263a",
    border:          "#2a2d3d",
    borderMid:       "#333650",
    text:            "#e8eaf0",
    textSub:         "#7a7f99",
    textMute:        "#454860",
    accent:          "#5b6af0",
    accentText:      "#fff",
    urgent:          "#e53935",
    urgentBg:        "#1a1010",
    soon:            "#e6a817",
    ok:              "#3d9e6a",
    cancelRed:       "#c62828",
    cancelRedBg:     "#2a1010",
    cancelRedBorder: "#8b2020",
    cancelRedText:   "#ef9a9a",
    headerBg:        "#12151f",
  } : {
    bg:              "#f4f5f8",
    surface:         "#ffffff",
    surfaceAlt:      "#f0f1f6",
    border:          "#dde0ec",
    borderMid:       "#c8cbdc",
    text:            "#1a1d2e",
    textSub:         "#5a5f7a",
    textMute:        "#a0a3b8",
    accent:          "#5b6af0",
    accentText:      "#fff",
    urgent:          "#d32f2f",
    urgentBg:        "#fff5f5",
    soon:            "#c77700",
    ok:              "#2e7d52",
    cancelRed:       "#c62828",
    cancelRedBg:     "#fff5f5",
    cancelRedBorder: "#e57373",
    cancelRedText:   "#b71c1c",
    headerBg:        "#ffffff",
  };
}
